### ISSUE TITLE
DNP_INSTALLER crashes when it isn't yet synchronized with the mainnet

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_INSTALLER#4]
The DNP_INSTALLER shows an error when you try to access from the DN_ADMINUI to the Installer and the mainnet isn't yet synchronized, also the DN_ADMINUI goes blank.

This situation should be controlled and the user should be warned that he can't install packages until the chain is synchronized.

DNP_INSTALLER error:
```
Error: Couldn't decode uint256 from ABI: 0x
    at SolidityTypeUInt.formatOutputUInt [as _outputFormatter] (/usr/src/app/node_modules/web3/node_modules/web3-eth-abi/src/formatters.js:174:15)
    at SolidityTypeUInt.SolidityType.decode (/usr/src/app/node_modules/web3/node_modules/web3-eth-abi/src/type.js:252:17)
    at /usr/src/app/node_modules/web3/node_modules/web3-eth-abi/src/index.js:327:49
    at Array.forEach (<anonymous>)
    at ABICoder.decodeParameters (/usr/src/app/node_modules/web3/node_modules/web3-eth-abi/src/index.js:326:13)
    at Contract._decodeMethodReturn (/usr/src/app/node_modules/web3/node_modules/web3-eth-contract/src/index.js:459:22)
    at Method.outputFormatter (/usr/src/app/node_modules/web3/node_modules/web3-eth-contract/src/index.js:811:46)
    at Method.formatOutput (/usr/src/app/node_modules/web3/node_modules/web3-core-method/src/index.js:162:54)
    at sendTxCallback (/usr/src/app/node_modules/web3/node_modules/web3-core-method/src/index.js:453:33)
    at Object.<anonymous> (/usr/src/app/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js:144:9)
    at /usr/src/app/node_modules/web3/node_modules/web3-providers-ws/src/index.js:76:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/usr/src/app/node_modules/web3/node_modules/web3-providers-ws/src/index.js:53:36)
```

DN_ADMINUI error:
```
PackageStore.js:60 Uncaught TypeError: Cannot read property 'length' of undefined
    at PackageDirectory.render (PackageStore.js:60)
    at finishClassComponent (react-dom.development.js:7873)
    at updateClassComponent (react-dom.development.js:7850)
    at beginWork (react-dom.development.js:8225)
    at performUnitOfWork (react-dom.development.js:10224)
    at workLoop (react-dom.development.js:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
    at renderRoot (react-dom.development.js:10366)
render @ PackageStore.js:60
finishClassComponent @ react-dom.development.js:7873
updateClassComponent @ react-dom.development.js:7850
beginWork @ react-dom.development.js:8225
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421
react-dom.development.js:9747 The above error occurred in the <PackageDirectory> component:
    in PackageDirectory (created by PackageInstallerInterface)
    in div (created by PackageInstallerInterface)
    in PackageInstallerInterface (created by Route)
    in Route (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Layout)
    in div (created by Layout)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Layout)
    in Layout

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Comment by eduadiez** [comment]
It also happens when the DNP_INSTALLER it isn't able to connect to the node

```
connection not open on send()
Error: connection not open
    at WebsocketProvider.send (/usr/src/app/node_modules/web3/node_modules/web3-providers-ws/src/index.js:219:18)
    at RequestManager.send (/usr/src/app/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js:129:66)
    at sendRequest (/usr/src/app/node_modules/web3/node_modules/web3-core-method/src/index.js:542:42)
    at send (/usr/src/app/node_modules/web3/node_modules/web3-core-method/src/index.js:563:13)
    at Object._executeMethod (/usr/src/app/node_modules/web3/node_modules/web3-eth-contract/src/index.js:819:24)
    at getDirectory (/usr/src/app/modules/createGetDirectory.js:25:103)
    at listDirectory (/usr/src/app/calls/createListDirectory.js:30:28)
    at Object.<anonymous> (/usr/src/app/index.js:124:22)
    at tryCatchResolve (/usr/src/app/node_modules/when/lib/apply.js:46:23)
    at callAndResolve (/usr/src/app/node_modules/when/lib/apply.js:30:12)
    at callAndResolveNext (/usr/src/app/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/usr/src/app/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/usr/src/app/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/usr/src/app/node_modules/when/lib/makePromise.js:588:4)
    at callAndResolve (/usr/src/app/node_modules/when/lib/apply.js:34:12)
    at callAndResolveNext (/usr/src/app/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/usr/src/app/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/usr/src/app/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/usr/src/app/node_modules/when/lib/makePromise.js:588:4)
    at callAndResolve (/usr/src/app/node_modules/when/lib/apply.js:34:12)
    at callAndResolveNext (/usr/src/app/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/usr/src/app/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/usr/src/app/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/usr/src/app/node_modules/when/lib/makePromise.js:588:4)
    at callAndResolve (/usr/src/app/node_modules/when/lib/apply.js:34:12)
    at apply (/usr/src/app/node_modules/when/lib/apply.js:23:4)
    at Object.attempt [as call] (/usr/src/app/node_modules/when/when.js:126:10)
    at Object.Session.self._process_INVOCATION (/usr/src/app/node_modules/autobahn/lib/session.js:788:18)
```
